### PR TITLE
Use ruby 2.6.6 and allow tests to be run

### PR DESCRIPTION
**Pull request by allison-strandberg**
This changes the ruby version used from 2.4.1 to 2.6.6, to match the version used in the mapdwell repo. This also allows `rake test` to be run: I'm not sure how to run the tests using ruby 2.4.1. The 'coveralls' test coverage gem was also removed, since it produced an error when running `rake test`.

2.6.6 appears to work fine: no test errors or failures were introduced.
`Finished in 12.511908s, 14.3064 runs/s, 24.1370 assertions/s.
179 runs, 302 assertions, 0 failures, 0 errors, 1 skips`

### CODE REVIEW

**Comment by waissbluth** [comment]
I have never seen a gem being so strict about ruby version, what error are you getting? Perhaps getting rid of the ruby-version and managing it via the gem's gemspec is cleaner. @volleio any ideas here?

**Comment by waissbluth** [comment]
oh wait, are you doing this to run the gem's tests or the app's test when using this gem?

**Comment by allison-strandberg** [comment]
@waissbluth to run the gem's tests.

**Review by waissbluth — APPROVED** [review]

**Comment by volleio** [comment]
I didn't think that the .ruby-version would affect a gem's compatibility, maybe it's just an issue with coveralls?
Their [gemspec](https://rubygems.org/gems/unitwise/versions/2.2.0) doesn't appear to specify a ruby version.

**Pull request merged**
